### ISSUE TITLE
Ember 2.1.0 Deprecation Checklist

### ISSUE THREAD

**Issue by rwjblue** [minichate/jscs-ember-deprecations#2]
- [x] [Initializer Arity](http://emberjs.com/deprecations/v2.x/#toc_initializer-arity)
- [x] [#registry on initializer / instance-initializer arguments](http://emberjs.com/deprecations/v2.x/#toc_ember-application-registry-ember-applicationinstance-registry)
- [x] [#container in instance-initializer](http://emberjs.com/deprecations/v2.x/#toc_ember-applicationinstance-container)
- [x] [Debug function arguments](http://emberjs.com/deprecations/v2.x/#toc_ember-debug-function-options)
- [x] [Ember.Component#defaultLayout](http://emberjs.com/deprecations/v2.x/#toc_ember-component-defaultlayout)
- [x] [Ember.Component#currentState](http://emberjs.com/deprecations/v2.x/#toc_ember-component-currentstate)
